angular.module('httpMocks')
  .run(function($httpBackend, $filter, $log, ngTableParams) {
    'use strict';
    $log.info('httpMocks loaded.');
    function gup( url, name ) {
      name = name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
      var regexS = "[\\?&]"+name+"=([^&#]*)";
      var regex = new RegExp( regexS );
      var results = regex.exec( url );
      if( results == null )
        return "";
      else
        return results[1];
    }
    // emulation of api server
    $httpBackend.whenGET(/geneListMock.*/)
      .respond(function(method, url) {
        var query = url.split('?')[1],
          requestParams = {};

        $log.log('Ajax request: ', url);

        var vars = query.split('&');
        for (var i = 0; i < vars.length; i++) {
          var pair = vars[i].split('=');
          requestParams[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1]);
        }

        var params;
        // parse url params
        for (var key in requestParams) {
          if (key.indexOf('[') >= 0) {
            var lastKey = '';
            var  value = requestParams[key];

            params = key.split(/\[(.*)\]/);
            angular.forEach(params.reverse(), function(name) {
              if (name !== '') {
                var v = value;
                value = {};
                value[lastKey = name] = _.isNumber(v) ? parseFloat(v) : v;
              }
            });
            requestParams[lastKey] = angular.extend(requestParams[lastKey] || {}, value[lastKey]);
          } else {
            requestParams[key] = _.isNumber(requestParams[key]) ? parseFloat(requestParams[key]) : requestParams[key];
          }
        }

        /* jshint ignore:start */
        var data = [
          {
            "entrez_gene":"ALK",
            "entrez_id":"19737948",
            "variant":"F1174L",
            "gene_category":"Receptor tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"",
            "pathway":"Cell proliferation and survival",
            "pathway_citation":"",
            "protein_motifs":"Signal peptide, MAM domain, LDL domain, MAM domain, transmembrane domain, juxtamembrane domain, kinase domain.",
            "motifs_citation":"21945349",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ALK",
            "entrez_id":"19737948",
            "variant":"R1275Q",
            "gene_category":"Receptor tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"",
            "pathway":"Cell proliferation and survival",
            "pathway_citation":"",
            "protein_motifs":"Signal peptide, MAM domain, LDL domain, MAM domain, transmembrane domain, juxtamembrane domain, kinase domain.",
            "motifs_citation":"21945349",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"EGFR",
            "entrez_id":"",
            "variant":"T790M",
            "gene_category":"Receptor tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"15142631",
            "pathway":"Angiogenesis, cell growth, cell migration and metastasis",
            "pathway_citation":"10690506",
            "protein_motifs":"Domain I, domain II, domain III, domain IV, transmembrane domain, kinase domain, regulatory region",
            "motifs_citation":"18573086",
            "mutation_biology":"Threonine to bulky methionine",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"EGFR",
            "entrez_id":"",
            "variant":"L858R",
            "gene_category":"Receptor tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"15142631",
            "pathway":"Angiogenesis, cell growth, cell migration and metastasis",
            "pathway_citation":"10690506",
            "protein_motifs":"Domain I, domain II, domain III, domain IV, transmembrane domain, kinase domain, regulatory region",
            "motifs_citation":"18573086",
            "mutation_biology":"Leucine to arginine",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"L536Q",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Small, Hydrophobic Leucine to Much Larger, Basic Glutamine.",
            "disease_ontology_id":"1612, 0060075, 1380",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Everolimus, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"Y537S",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Large Tyrosine to Smaller Serine. Biochemically very similar.",
            "disease_ontology_id":"1612, 0060075, 1380",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Toremifene, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"Y537C",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Tyrosine to Cysteine.",
            "disease_ontology_id":"breast, endometrial, ovarian",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Toremifene, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"Y537N",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Tyrosine to Asparagine",
            "disease_ontology_id":"1612, 0060075, 1380",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Toremifene, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"N538G",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Large Asparagine to Much Smaller Glycine.",
            "disease_ontology_id":"1612, 0060075, 1380",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Toremifene, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ESR1",
            "entrez_id":"2099",
            "variant":"Amplification",
            "gene_category":"Nuclear Hormone Receptor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand Activated Transcription  Factor",
            "function_citation":"21779010",
            "pathway":"Hormone (Estrogen) Response",
            "pathway_citation":"16769596",
            "protein_motifs":"DNA binding domain, Dimer binding site, Ligand binding domain.",
            "motifs_citation":"24185510",
            "mutation_biology":"Large Asparagine to Much Smaller Glycine.",
            "disease_ontology_id":"1612, 0060075, 1380",
            "type_citation":"24185510",
            "treatments":"Tamoxifen, Toremifene, Anastrozole, Letrozole",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ESR1 encodes for the Estrogen Receptor alpha subunit, a Nuclear Hormone Receptor. It's cellular function is to bind its ligand, estrogen, and modulate transcription of genes responsible for hormone response. It is integral to sexual and reproductive development. The protein contains a DNA-binding domain which dimerizes to another alpha or beta subunit to form a functional transcription factor. It also contains a Ligand Binding Domain (LBD) which has been found to be a hotspot for mutations in Breast and Endometrial Cancer. Computational predictions have shown that ligand binding domain mutations are capable of being activating mutations, and in vitro experiments have confirmed the constitutive acitivity of LBD mutations. A number of drugs are already FDA approved to treat ESR1 abnormalities in Breast Cancer, these include: Tamoxifen, Everolimus, and the aromatase inhibitors Anastrozole and Letrozole. A full list of drugs that interact with ESR1 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"V777L",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Valine to Isoleucine, both very similar, hydrophobic amino acids within the kinase domain",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"ERBB2 (commonly known as HER2) encodes for a receptor tyrosine kinase that is involved in the mitogen-activated cell growth and proliferation pathway. While it does not bind a ligand, its function is to form an active heterodimer with EGFR upon it's ligand binding, which results in the cross-phosphorylation of its tyrosine kinase domain. This domain, when activated, acts as a docking site for downstream enzymes responsible for propagating the kinase cascade, including SHC, Grb and SOS. It contains a few notable functional domains, including an extracellular region, dimerization region, tyrosine phosphorylation sites, and an anchoring site for the transducers of the kinase cascade. This mutation specifically convert Valine to Isoleucine, which are similar in structure. However, in vitro kinase activity assays have shown that this mutation is an activating one, and produces a very significant increase in activity of both the monomer and dimer forms of the protein. This mutation has also been shown to exhibit sensitivity to the kinase inhibitor neratinib, an FDA approved drug for ERBB2 amplification in Breast Cancer. A full list of drugs that interact with ERBB2 can be found at www.dgidb.org",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"DEL 755-759",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Deletion of four amino acids in kinase domain, possibly a loss of function mutation",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"L755S",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Leucine mutated to Serine in the kinase domain of the protein. A hydrophobic amino acid is being converted to a hydrophillic residue of similar size.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"D769H",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Aspartic Acid converted to Histamine. An acidic residue is converted to the very basic histamine within the kinase domain.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"V842I",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Valine to Isoleucine, both very similar, hydrophobic amino acids within the kinase domain",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"G309A",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Glycine to Alanine, both small, hydrophobic amino acids. Mutation is within the dimerization domain.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"R678Q",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Arginine to Glutamine, both relatively basic amino acids. Mutation is immediately ater the trans-membrane domain, within the cytoplasmic side of the protein.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"L755W",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Leucine to Tryptophan. A small, hydrophobic amino acid, to a much larger one. Mutation is within the kinase domain.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ERBB2",
            "entrez_id":"2064",
            "variant":"Amplification",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"EGFR related signal transducer",
            "function_citation":"Entrez Gene",
            "pathway":"Mitogen Activated cell growth and proliferation",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Leucine to Tryptophan. A small, hydrophobic amino acid, to a much larger one. Mutation is within the kinase domain.",
            "disease_ontology_id":"1612, 0060079, 2394, 1793, 1380, 3908, 11812, 3717",
            "type_citation":"17471238, 20185938",
            "treatments":"Trastuzumab, Pertuzumab, Lapatinib, Neratinib",
            "treatments_citation":"http://www.accessdata.fda.gov/scripts/cder/drugsatfda/index.cfm",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"PIK3CA",
            "entrez_id":"5290",
            "variant":"E542K",
            "gene_category":"Lipid Signalling",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Lipid signalling cascadetransducer",
            "function_citation":"Entrez Gene",
            "pathway":"Lipid Signalling, Calcium Signalling.",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Catalytic kinase domain, Multiple protein binding sites.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Glutamic Acid to basic Lysine",
            "disease_ontology_id":"Colon, Breast, Urinary, Endometrial",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"PIK3CA",
            "entrez_id":"5290",
            "variant":"E545K",
            "gene_category":"Lipid Signalling",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Lipid signalling cascadetransducer",
            "function_citation":"Entrez Gene",
            "pathway":"Lipid Signalling, Calcium Signalling.",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Catalytic domain, Multiple protein binding sites.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Glutamic Acid to basic Lysine",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"PIK3CA",
            "entrez_id":"5290",
            "variant":"H1047R",
            "gene_category":"Lipid Signalling",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Lipid signalling cascadetransducer",
            "function_citation":"Entrez Gene",
            "pathway":"Lipid Signalling, Calcium Signalling.",
            "pathway_citation":"Entrez Gene",
            "protein_motifs":"Catalytic domain, Multiple protein binding sites.",
            "motifs_citation":"Entrez Gene",
            "mutation_biology":"Histidine to Arginine",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"GATA3",
            "entrez_id":"",
            "variant":"",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"BRAF",
            "entrez_id":"673",
            "variant":"V600E",
            "gene_category":"serine/threonine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Raf activated MEK kinase",
            "function_citation":"7855890",
            "pathway":"Cell survival signal",
            "pathway_citation":"7855890",
            "protein_motifs":"Ras binding domain, Thr Ser rich region, kinase region",
            "motifs_citation":"20674547",
            "mutation_biology":"",
            "disease_ontology_id":"Thyroid, colorectal, melanoma, ovarian",
            "type_citation":"12670889",
            "treatments":"",
            "treatments_citation":"",
            "summary":"The BRAF gene provides instructions for making a protein that helps transmit chemical signals from outside the cell to the cell's nucleus. This protein is part of a signaling pathway known as the RAS/MAPK pathway, which helps control several important cell functions. Specifically, the RAS/MAPK pathway regulates the growth and division (proliferation) of cells, the process by which cells mature to carry out specific functions (differentiation), cell movement (migration), and the self-destruction of cells (apoptosis). Chemical signaling through this pathway is essential for normal development before birth.",
            "event_summary":"BRAF V600E has been shown to be recurrent in many cancer types. It is one of the most widely studied variants in cancer. This variant is correlated with poorprognosis in certain cancer types, including CRC and papillary thyroid cancer. The targeted therapeutic debrafenib has been shown to be effective in clinical trials with an array of BRAF mutations. Debrafenib has also shown to be effective when combined with the MEK inhibitor trametinib in CRC and melanoma. However, in patients with TP53, KRAS, and CDK2NA mutations, debrafenib resistance has been reported. Ipilimumab, regorafenib, vemurafenib, and a number of combination therapies have been successful in treating V6000E mutations. While the drugs cetuximab and panitumumab have largely shown to been largely ineffective without supplementary treatment.",
            "clinical_trial":""
          },
          {
            "entrez_gene":"FLT3",
            "entrez_id":"2322",
            "variant":"D835",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"21359601",
            "pathway":"Cell proliferation signal",
            "pathway_citation":"8590775",
            "protein_motifs":"extracellular immunoglobulin-like domains, transmembrane domain, juxtamembrane domain and tyrosine-kinase domains",
            "motifs_citation":"8590775",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MPL",
            "entrez_id":"",
            "variant":"W515",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"KIT",
            "entrez_id":"3815",
            "variant":"D816V (exon 17)",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"15526160",
            "pathway":"Cell survival and differentiation signal",
            "pathway_citation":"15526160",
            "protein_motifs":"extracellular domain, transmembrane segment, juxtamembrane domain, protein kinase domain",
            "motifs_citation":"16226710",
            "mutation_biology":"",
            "disease_ontology_id":"Small cell lung cancer, breast cancer, colorectal cancer, GIST",
            "type_citation":"15526160",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"KIT",
            "entrez_id":"3815",
            "variant":"L576P (exon 11)",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"15526160",
            "pathway":"Cell survival and differentiation signal",
            "pathway_citation":"15526160",
            "protein_motifs":"extracellular domain, transmembrane segment, juxtamembrane domain, protein kinase domain",
            "motifs_citation":"16226710",
            "mutation_biology":"",
            "disease_ontology_id":"Melanoma, lung",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"JAK2",
            "entrez_id":"3717",
            "variant":"V617F",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"24069563",
            "pathway":"Cell survival, anti-apoptotic and cell cycle control signal",
            "pathway_citation":"24058805",
            "protein_motifs":"Receptor region, binding region, pseudokinase region, kinase region",
            "motifs_citation":"12039028",
            "mutation_biology":"",
            "disease_ontology_id":"8997, 2224, 4971, 8552, 9119",
            "type_citation":"Genetics Home Reference",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"IDH1",
            "entrez_id":"3417",
            "variant":"R132H",
            "gene_category":"Reductase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"oxidize isocitrate to alpha-ketoglutarate (_-KG)",
            "function_citation":"23512379",
            "pathway":"cell metabolism",
            "pathway_citation":"23999441",
            "protein_motifs":"nucleotide binding, substrate binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"IDH1",
            "entrez_id":"3417",
            "variant":"R132C/S",
            "gene_category":"Reductase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"oxidize isocitrate to alpha-ketoglutarate (_-KG)",
            "function_citation":"23512379",
            "pathway":"cell metabolism",
            "pathway_citation":"23999441",
            "protein_motifs":"nucleotide binding, substrate binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"IDH2",
            "entrez_id":"",
            "variant":"R140Q/L",
            "gene_category":"Reductase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"oxidize isocitrate to alpha-ketoglutarate (_-KG)",
            "function_citation":"23512379",
            "pathway":"cell metabolism",
            "pathway_citation":"23999441",
            "protein_motifs":"nucleotide binding, substrate binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"IDH2",
            "entrez_id":"",
            "variant":"R172K",
            "gene_category":"Reductase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"oxidize isocitrate to alpha-ketoglutarate (_-KG)",
            "function_citation":"23512379",
            "pathway":"cell metabolism",
            "pathway_citation":"23999441",
            "protein_motifs":"nucleotide binding, substrate binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"p.G13D",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"p.Q61H",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"Q61K",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"G12D",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"Q61R",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NRAS",
            "entrez_id":"4893",
            "variant":"G12C",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"KRAS",
            "entrez_id":"4893",
            "variant":"Q61H",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"20921338",
            "pathway":"Cell survival, cell growth, cell migration, cell division",
            "pathway_citation":"22983396",
            "protein_motifs":"GTP binding, hypervariable region, effector binding",
            "motifs_citation":"Uniprot",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"KRAS",
            "entrez_id":"",
            "variant":"G12V/D",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"10989276",
            "pathway":"cell proliferation, differentiation, survival",
            "pathway_citation":"9009833",
            "protein_motifs":"GTP binding, effector binding, hypervariable region",
            "motifs_citation":"23626007",
            "mutation_biology":"",
            "disease_ontology_id":"Lung cancer, colorectal cancer, leukemia",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"KRAS",
            "entrez_id":"",
            "variant":"G13D",
            "gene_category":"GTP binding tyrosine kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"small GTPase transductor protein",
            "function_citation":"10989276",
            "pathway":"cell proliferation, differentiation, survival",
            "pathway_citation":"9009833",
            "protein_motifs":"GTP binding, effector binding, hypervariable region",
            "motifs_citation":"23626007",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"U2AF",
            "entrez_id":"7307",
            "variant":"S34Y/F",
            "gene_category":"RNA binding protein",
            "gene_category_citation":"Uniprot",
            "protein_function":"protein-RNA binding mediator",
            "function_citation":"12127445",
            "pathway":"Protein translation",
            "pathway_citation":"22158538",
            "protein_motifs":"Zinc finger, RNA recognition domain",
            "motifs_citation":"23775717",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"U2AF",
            "entrez_id":"7307",
            "variant":"Q157P/R",
            "gene_category":"RNA binding protein",
            "gene_category_citation":"Uniprot",
            "protein_function":"protein-RNA binding mediator",
            "function_citation":"12127445",
            "pathway":"Protein translation",
            "pathway_citation":"22158538",
            "protein_motifs":"Zinc finger, RNA recognition domain",
            "motifs_citation":"23775717",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"DNMT3A",
            "entrez_id":"",
            "variant":"R882C/S",
            "gene_category":"Methyltransferase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA methyltransferase",
            "function_citation":"10545955",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"Variable region, PWWP region, cystein rich region, catalytic region",
            "motifs_citation":"15456878",
            "mutation_biology":"",
            "disease_ontology_id":"9119",
            "type_citation":"Genetics Home Reference",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"DNMT3A",
            "entrez_id":"",
            "variant":"R882H",
            "gene_category":"Methyltransferase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA methyltransferase",
            "function_citation":"10545955",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"Variable region, PWWP region, cystein rich region, catalytic region",
            "motifs_citation":"15456878",
            "mutation_biology":"",
            "disease_ontology_id":"9119",
            "type_citation":"Genetics Home Reference",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"FLT3",
            "entrez_id":"",
            "variant":"D835E",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"8618433",
            "pathway":"cell proliferation",
            "pathway_citation":"8590775",
            "protein_motifs":"Ig-like domain, transmembrane domain, juxtamembrane domain, tyrosine kinase domain",
            "motifs_citation":"14759363",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"FLT3",
            "entrez_id":"",
            "variant":"D835Y",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"8618433",
            "pathway":"cell proliferation",
            "pathway_citation":"8590775",
            "protein_motifs":"Ig-like domain, transmembrane domain, juxtamembrane domain, tyrosine kinase domain",
            "motifs_citation":"14759363",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"FLT3",
            "entrez_id":"",
            "variant":"D839G",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"8618433",
            "pathway":"cell proliferation",
            "pathway_citation":"8590775",
            "protein_motifs":"Ig-like domain, transmembrane domain, juxtamembrane domain, tyrosine kinase domain",
            "motifs_citation":"14759363",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"FGFR2",
            "entrez_id":"",
            "variant":"",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SF3B1",
            "entrez_id":"",
            "variant":"K700E",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SF3B1",
            "entrez_id":"",
            "variant":"K666N",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"CSF3R",
            "entrez_id":"",
            "variant":"T618I",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"GATA2",
            "entrez_id":"",
            "variant":"T354M",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"GATA2",
            "entrez_id":"",
            "variant":"R398W",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"Y220C",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"1612, 11054, 9256",
            "type_citation":"Genetics Home Reference",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"R249T",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"R249W",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"R248Q",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"R273H",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"R273C",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"TP53",
            "entrez_id":"",
            "variant":"V173G/A",
            "gene_category":"Tumor suppressor",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"DNA binding transactivation factor",
            "function_citation":"12446780",
            "pathway":"Cell cycle arrest, senescence and apoptosis",
            "pathway_citation":"15865944",
            "protein_motifs":"Activation domain, prolin rich domain, DNA binding domain, nuclear localization signal, tetramerization domain, basic domain",
            "motifs_citation":"16543939",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"RUNX1",
            "entrez_id":"",
            "variant":"R201*",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"RUNX1",
            "entrez_id":"",
            "variant":"R162K",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"RUNX1",
            "entrez_id":"",
            "variant":"R162S",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"RUNX1",
            "entrez_id":"",
            "variant":"R162G",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"WT1",
            "entrez_id":"",
            "variant":"A381fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"WT1",
            "entrez_id":"",
            "variant":"A381fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"WT1",
            "entrez_id":"",
            "variant":"A381fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MIR142",
            "entrez_id":"",
            "variant":"-",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MIR142",
            "entrez_id":"",
            "variant":"-",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MIR142",
            "entrez_id":"",
            "variant":"-",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NPM1",
            "entrez_id":"",
            "variant":"W288fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NPM1",
            "entrez_id":"",
            "variant":"W288fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NPM1",
            "entrez_id":"",
            "variant":"W288fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NPM1",
            "entrez_id":"",
            "variant":"W288fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"NPM1",
            "entrez_id":"",
            "variant":"W288fs",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SRSF2",
            "entrez_id":"",
            "variant":"P95H",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SRSF2",
            "entrez_id":"",
            "variant":"P95L",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SRSF2",
            "entrez_id":"",
            "variant":"P95R",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SRSF2",
            "entrez_id":"",
            "variant":"P95A",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"SRSF2",
            "entrez_id":"",
            "variant":"P95T",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"CBL",
            "entrez_id":"",
            "variant":"Y371",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"JAK1",
            "entrez_id":"",
            "variant":"V658F",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ABL",
            "entrez_id":"",
            "variant":"",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"ARAF",
            "entrez_id":"369",
            "variant":"S214C",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"nuclear signal transducer",
            "function_citation":"",
            "pathway":"Cell cycle control, cell proliferation",
            "pathway_citation":"9779991",
            "protein_motifs":"RAS binding domain, cysteine-rich domain, catalytic domain",
            "motifs_citation":"10848612",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"PDGFRA",
            "entrez_id":"5156",
            "variant":"D842V",
            "gene_category":"Receptor Tyrosine Kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"15207812",
            "pathway":"Cell survival and differentiation signal",
            "pathway_citation":"18483217",
            "protein_motifs":"Ig-like domain, transmembrane domain, Split-tyrosine kinase domain",
            "motifs_citation":"8586421",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MAP2K1",
            "entrez_id":"5604",
            "variant":"Q56P",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"MAP2K1",
            "entrez_id":"5604",
            "variant":"P124S",
            "gene_category":"",
            "gene_category_citation":"",
            "protein_function":"",
            "function_citation":"",
            "pathway":"",
            "pathway_citation":"",
            "protein_motifs":"",
            "motifs_citation":"",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          },
          {
            "entrez_gene":"RET",
            "entrez_id":"5979",
            "variant":"M918T",
            "gene_category":"Receptor tyrosine-protein kinase",
            "gene_category_citation":"Entrez Gene",
            "protein_function":"Ligand activated kinase",
            "function_citation":"uniprot",
            "pathway":"Cell survival, cell proliferation, cell migration",
            "pathway_citation":"11544105",
            "protein_motifs":"Cystein rich, transmembrane, tyrosine kinase 1, tyrosine kinase 2",
            "motifs_citation":"11114739",
            "mutation_biology":"",
            "disease_ontology_id":"",
            "type_citation":"",
            "treatments":"",
            "treatments_citation":"",
            "summary":"",
            "event_summary":"",
            "clinical_trial":""
          }
        ];
        /* jshint ignore:end */

        params = new ngTableParams(requestParams);
        data = params.filter() ? $filter('filter')(data, params.filter()) : data;
        data = params.sorting() ? $filter('orderBy')(data, params.orderBy()) : data;

        var total = data.length;
        data = data.slice((params.page() - 1) * params.count(), params.page() * params.count());

        return [200, {
          result: data,
          total: total
        }];
      });
    $httpBackend.whenGET(/geneDataMock.*/)
      .respond(function(method, url) {
        $log.log('Ajax request: ', url);

        var data = {
          name: gup(url, 'id'),
          summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend nec nulla sit amet euismod. Aliquam faucibus tellus neque. Quisque sed dui quis nulla efficitur fermentum sit amet sit amet eros. Pellentesque porttitor dolor lectus, in ullamcorper ante fringilla placerat. Praesent porttitor vestibulum lectus, eget lacinia nibh rhoncus ut. Nulla vel mi sagittis, eleifend tellus ut, placerat eros. Nullam pharetra, ipsum vitae tempus mollis, purus leo consectetur quam, sit amet hendrerit libero sem nec quam. Nulla viverra enim non bibendum mollis.",
          metrics: {
            "Therapies": 'Trastuzumab, Pertuzumab, Lapatinib, Neratinib',
            "Diseases": 'Breast Cancer, Leukemia',
            "Protein Function": 'EGFR related signal transducer',
            'Pathway(s)s': 'Mitogen Activated cell growth and proliferation',
            'Protein Motifs': 'Dimerization site, Tyrosine phosphorylation sites, kinase cascade anchor site'
          },
          events: ["VARIANT1", "VARIANT2", "VARIANT3", "VARIANT4", "VARIANT5"],
          eventGroups: {
            "EVTGRP": ["VARIANT6", "VARIANT7"],
            "EVTGRP2": ["VARIANT8", "VARIANT9"]
          }
        };

        return [200, { result: data }];
      });

    $httpBackend.whenGET(/eventDataMock.*/)
      .respond(function(method, url) {
        'use strict';
        /* jshint ignore:start */
        var data = {
          "entrez_gene":"BRAF",
          "variant":"V600E",
          "summary":"BRAF V600E has been shown to be recurrent in many cancer types. It is one of the most widely studied variants in cancer. This variant is correlated with poorprognosis in certain cancer types, including CRC and papillary thyroid cancer. The targeted therapeutic debrafenib has been shown to be effective in clinical trials with an array of BRAF mutations. Debrafenib has also shown to be effective when combined with the MEK inhibitor trametinib in CRC and melanoma. However, in patients with TP53, KRAS, and CDK2NA mutations, debrafenib resistance has been reported. Ipilimumab, regorafenib, vemurafenib, and a number of combination therapies have been successful in treating V6000E mutations. While the drugs cetuximab and panitumumab have largely shown to been largely ineffective without supplementary treatment.",
          "details": {
            "Clinical Action Statements": 5,
            "Another Metric": 10
          },
          evidence:  [{ "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "V600E is associated with adverse pathological features of CRC This can be concluded as poor prognosis", "level": "A", "source": "24594804", "text": "", "type_of_study": "Metaanalysis", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Debrafenib", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "patients with V600E mutation other than V600E also respond well to V600E drug Debrafenib", "level": "B", "source": "23031422", "text": "", "type_of_study": "Case report", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Debrafenib", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "patients with V600E mutation as well as V600E respond well to V600E drug Debrafenib", "level": "B", "source": "23463675", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Debrafenib, trametinib", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "Debrafenib with trametinib provides higher response rate and lower toxicity in patients with melanoma", "level": "B", "source": "24583796", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Dacarbazine, Temozolomide", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF status does not predict prognosis in patients treated with dacarbazine or temozolomide", "level": "B", "source": "24586605", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Diagnostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "thyroid nodule with BRAF V600E mutation is highly correlated with thyroid cancer", "level": "B", "source": "24574369", "text": "", "type_of_study": "case report", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Diagnostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "thyroid nodule with BRAF V600E mutation is highly correlated with thyroid cancer", "level": "B", "source": "24588959", "text": "", "type_of_study": "Perspective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Diagnostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "thyroid nodule with BRAF V600E mutation is highly correlated with thyroid cancer", "level": "B", "source": "24570209", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Ipilimumab, Debrafenib", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "treatment with immunotherapy (e.g. Ipilimumab) prior to RAF inhibitor (e.g. Debrafenib) appears to be beneficial, and better than vice versa.", "level": "B", "source": "24577748", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "In the setting of BRAF(V600E), NF1 loss resulted in elevated activation of RAS-GTP and resistance to RAF, but not MEK, inhibitors.", "level": "C", "source": "24576830", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal cancer", "disease_ontology_id": "", "drug": "Regrorafinib", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "regrorafinib may be effective in those not responding to BRAF", "level": "B", "source": "24559322", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF mutation correlated with poor prognosis in papillary thyroid cancer in some studies", "level": "B", "source": "24396464", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF mutation correlated with poor prognosis in papillary thyroid cancer in some studies", "level": "B", "source": "24388723", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF mutation correlated with poor prognosis in papillary thyroid cancer in some studies", "level": "B", "source": "21594703", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Thyroid cancer", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF mutation correlated with improved prognosis in papillary thyroid cancer in some studies", "level": "B", "source": "24354346", "text": "", "type_of_study": "Retrospective study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "in brain cancer resulting from melanoma metastisis, Vemurafenib is an effective treatment", "level": "B", "source": "24295639", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal cancer", "disease_ontology_id": "", "drug": "MK-2206, vemurafenib, bevacizumab", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "colorectal cancer cells treated with combination therapy (braf inhibitor, Akt inhibitor, EGFR inhibitor ) showed better outcome.", "level": "C", "source": "22180495", "text": "", "type_of_study": "In vivo study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal cancer", "disease_ontology_id": "", "drug": "panitumumab", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "in patients with metastatic colorectal cancer, treatment with panitumumab is ineffective", "level": "B", "source": "23325582", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Diagnostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "BRAF V600E resistance is triggered by ERK dependent or independent pathways", "level": "C", "source": "21505228", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "", "disease_ontology_id": "", "drug": "", "type_of_evidence": "Diagnostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "amplification of BRAF V600E gene leads to resistance to MEK and BRAF inhibition", "level": "C", "source": "21098728", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Melanoma", "disease_ontology_id": "", "drug": "Debrafenib, trametinib", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "combined BRAF and MEK inhibition using Debrafenib and trametinib leads to enhanced survival and disease response rate", "level": "B", "source": "23020132", "text": "", "type_of_study": "Clinical trial", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal", "disease_ontology_id": "", "drug": "PD0325901, PLX4720", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "MEK inhibition together with BRAF inhibition may be beneficial for colorectal cancer with V600E mutation", "level": "C", "source": "23845441", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal", "disease_ontology_id": "", "drug": "GDC-0879, BEZ235", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "PI3K inhibition together with BRAF inhibition may be beneficial for colorectal cancer with V600E mutation", "level": "C", "source": "23812671", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Lung cancer", "disease_ontology_id": "", "drug": "Debrafenib", "type_of_evidence": "Prognostic", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "Resistance to Debrafinib can arise from TP53, KRAS, and CDKN2A mutation during therapy", "level": "B", "source": "23524406", "text": "", "type_of_study": "case report", "comments": "", "curator": "" }, { "entrez_gene": "BRAF", "entrez_id": "673", "variant": "V600E", "disease": "Colorectal", "disease_ontology_id": "", "drug": "cetuximab, panitumumab, sorafenib", "type_of_evidence": "Predictive", "evidence_outcome": "", "direction_for_clinical_actionability": "", "explanation": "cetuximab or panitumumab may be ineffective in patients with BRAF mutation unless BRAF inhibitor such as Sorafenib is introduced", "level": "C", "source": "19001320", "text": "", "type_of_study": "In vitro study", "comments": "", "curator": "" }]
        };
        /* jshint ignore:end */

        return [200, data]
      });

    $httpBackend.whenGET(/.*/).passThrough();
  });